# Generated by Django 3.2.4 on 2021-07-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0002_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='usuario',
            new_name='user',
        ),
    ]
