# Generated by Django 3.2.4 on 2021-07-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
